name: 'GitHub Action for Firebase node version 16'
author: 'Jeremy Shore'
description: 'Wraps the firebase-tools CLI to enable common commands.'
branding:
  icon: 'package'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'docker://vsuhanov/firebase-action:latest'
